site_name: DevSecOps Pipeline
nav:
  - Introduction: 'index.md'
  - Table of Content: 'contents.md'
  - Problem Statement: 'problem_statements.md'
  - Setup of VMs: 'vm_setup.md'
  - Setup of Jenkins: 'jenkins_setup.md'
  - Setup of Production Server: 'production_setup.md'
  - SSH Connection between VMs: 'ssh_connection.md'
  - Working of Pipeline: 'working_of_pipeline.md'
  - Static Analysis: 'static_analysis.md'
  - Software Composition Analysis: 'sca.md'
  - Dynamic Analysis: 'dynamic_analysis.md'
  - Software Bill of Materials: 'sbom.md'
  - Software Code Quality Analysis: 'scqa.md'
  - Complete Pipeline: 'complete_pipeline.md'
  - Resources: 'resources.md'
theme: material
