site_name: DevSecOps Pipeline
nav:
  - Introduction: 'index.md'
  - Table of Content: 'contents.md'
  - Setup of VMs: 'vm_setup.md'
  - Setup of Jenkins: 'jenkins_setup.md'
  - Setup of Production Server: 'production_setup.md'
  - SSH Connection between VMs: 'ssh_connection.md'
  - Static Analysis: 'static_analysis.md'
  - Dynamic Analysis: 'dynamic_analysis.md'
  - Resources: 'resources.md'
theme: material

