site_name: DevSecOps Pipeline
nav:
  - Introduction: 'index.md'
  - Setup of VMs: 'vm_setup.md'
  - Setup of Jenkins: 'jenkins_setup.md'
  - Setup of Production Server: 'production_setup.md'
  - SSH Connection between VMs: 'ssh_connection.md'
  - SAST using NodeJsScan: 'nodejsscan_sast.md'

theme: material

